# TODO: this may be better closer to their class implementations.

ITEM_QUALITY_LOWER_BOUND = 0
ITEM_QUALITY_UPPER_BOUND = 50
ITEM_QUALITY_DETERIORATION_RATE = 1
ITEM_OVERDUE_FACTOR = 2

LEGENDARY_ITEM_QUALITY = 80

SMELLY_ITEMS_DETERIORATION_RATE = 2 * ITEM_QUALITY_DETERIORATION_RATE

BACKSTAGE_QUALITY_THRESHOLDS = {
    10.0: 1 * ITEM_QUALITY_DETERIORATION_RATE,
    5.0: 3 * ITEM_QUALITY_DETERIORATION_RATE,
    -1: 0 * ITEM_QUALITY_DETERIORATION_RATE

}
